---
title: "Hex Grid"
output: html_document
date: "2023-07-20"
---

# Setting up

```{r}
library(sf)
```

# Reading in the data

## Hexagonal grid

Reading the data as a hex grid

```{r}
input_path <- "data/features"
files <- list.files(input_path, pattern = "[.]gpkg$", full.names=T)
for (f in files){
  # read in file
  shp <- st_read(f)
  shp <- shp %>% st_transform(3857) 
  # drop unnecessary columns - only keep grid id and geometry
  keep_column <- c("grid_id")
  shp <- shp[,(names(shp) %in% keep_column)]
  # get name to save
  city_name <- gsub(".*data/features/(.+)_all_features.gpkg.*", "\\1", f)
  shp_name <- paste0(city_name, "_hex_grid")
  # save with new name
  assign(paste(shp_name), st_sf(shp), envir = .GlobalEnv)
}
# remove the temporary objects
rm(shp)
```

### Municipal boundaries

Reading in the municipal boundaries 

- Brazil

```{r}
brazil <- st_read("gadm41_BRA_shp/gadm41_BRA_2.shp")
brazil <- brazil %>% st_transform(3857)
```

- Colombia

```{r}
colombia <- st_read("gadm41_COL_shp/gadm41_COL_2.shp")
colombia <- colombia %>% st_transform(3857)
```

- Mexico

```{r}
mexico <- st_read("gadm41_MEX_shp/gadm41_MEX_2.shp")
mexico <- mexico %>% st_transform(3857)
```



# Outputs

```{r}
hex_grid_dfs <- mget(grep('hex_grid', names(which(unlist(eapply(.GlobalEnv,is.data.frame)))), value = TRUE))
```

```{r}
# save their outputs
for(i in 1:length(hex_grid_dfs)) {
## construct a file name and save this data:
  file.name = paste0("data/hex_grid/", names(hex_grid_dfs)[i], ".shp")
  st_write(hex_grid_dfs[[i]], file.name)
}
```